### PR TITLE
pull request of  Chinsese translation

### PR DESCRIPTION
**Pull request by yangkang5303**
hi this is Chinsese (simplified)for chapter 2.2~2.3

### CODE REVIEW

**Comment by medied** [comment]
Wonderful! Thank you @yangkang5303 for the effort 👏

**Comment by SFSandra** [comment]
Much appreciated @yangkang5303 ! 🙏

**Comment by yangkang5303** [comment]
You are welcome folks, let's make this planet a better one.

**Comment by virgile-dev** [comment]
Amazing ! Thank you so much @yangkang5303 !

**Pull request merged**
