### PR TITLE
Update FAQ.md

### PR DESCRIPTION
**Pull request by dfpoon**
typo fixed - in "addition" to

### CODE REVIEW

**Comment by medied** [comment]
Hello @dfpoon, thanks for catching those typos and contributing to the project 🙂. There's a slight conflict right now because the `FAQ.md` you modified is now named `FAQ-en.md` and it's under a new directory `FAQ/`. I can fix this manually from my end, but I believe that way your username wouldn't get registered in the list of contributors. Would you like to be acknowledge for your contribution? If so, can you resubmit the PR? If not, just let me know and I will merge manually.

I think it's neat to have all contributors acknowledged, but up to you!

**Comment by medied** [comment]
This also includes PR #242, If you want to resubmit you can probably lump the two typos in one PR. Again if you don't care, no worries I'll merge manually.

**Comment by dfpoon** [comment]
Thanks for your response. I don't mind skipping my name. (frankly speaking my contribution is so tiny.)

I would like to take this opportunity to suggest correcting two more typos:
Q17. no single point of "faillure" --> failure
Q19. What is a descentralized ID (DID)?  --> decentralized

Thanks!

**Comment by SFSandra** [comment]
Hi @medied and @dfpoon I made the correction to those 2 typos, thanks @dfpoon for pointing them out!!

**Comment by medied** [comment]
@dfpoon tiny contributions are powerful too! So thanks again, I will fix the two original typos now. And yes @SFSandra thanks for catching the other two typos! All four will be resolved after my commit coming up.

**Pull request closed without merging**
