### PR TITLE
remove blackwater story

### PR DESCRIPTION
**Pull request by piamancini**
Several reasons: 
- we can't quote him without his/her permission. 
- if we do, we must remove context, he/she can easily be singled out from the YC reference. This can be dangerous for the source's life. 
- if we believe that quoting them is not putting them at risk, then the quote is likely been blown out of proportion in which case I would insist it's removed. 
- there is no concrete evidence 
- it's a red herring.

### CODE REVIEW

**Comment by santisiri** [comment]
I think we need to share a clear story on AI. This is a first hand experience. What would you suggest?

**Comment by dwightmwilson** [comment]
i commented a few minutes ago under "Issues" where Pia had provided a comment - I"m now wondering if all we need to say under AI is that, like climate change, there is no other urgent issue that more desperately needs true discussion, deliberation and actual governance of the global crowd, of all 7.5B of us.  Our readers won't need examples to understand this. DEF has helped me more clearly see every day that too few people worldwide are making key decisions for the many - both in democracies of all levels of inclusion and in autocracies. (This includes all US Presidents, not just Trump but Obama and Bush and Clinton etc - the system is more the issue than the individual.)

**Comment by SFSandra** [comment]
Why not leave the story in but replace the specific Blackwater reference with 'well known defense contractor' - it's a first hand experience story, so tacitly understood that you're not going to disclose details that might be endangering. 

I personally found the whole AI section totally appropriate,  both edifying and alarming, and well defended, if a bit long  - like taking a side path at the beginning of the journey and suddenly finding myself on what feels like a different journey, wondering if I've lost the narrative thread.   

I think the BW story literally and critically (and first hand!)  illustrates how we're living in an era when AI decides the fate of human lives (but doesn't need to have BW identified for the point still to be made).  I think the timing to include this is good, with Elon Musk in the news recently,  public and urgent with this same message about AI development, that this opens up ethical and moral and even liberty and justice questions. 

For me the real lightning rod in this section was the fact that Palantir employees are offering the so-called 'devil’s advocate argument' of  “would you rather trust a stressed human unaware of all the variables or rather an AI capable of processing multiple factors at once?”  I mean, holy shit it's REALLY scary someone would ask that - the implications of this kind of persuasive tactic are terrifying.... For one, it's chillingly ingenious disinformation, the kind of tactic you see from  only the most skilled propagandist/true believer, to wit: that emotions are somehow the opposite of logic and reason, not to be as trusted as 'objective' machines. Get people to buy that and then have a lock on the government contracts for providing those objective deciding machines that we trust more than people.....let's see, what kind of company makes that AI? Oh, I know - Palantir.  Suddenly ol' Peter Thiele is going to be a lot richer.  This is what Elon Musk is warning about: let's not wait for police department owned, Palantir-controlled AI to start conducting arrests, illegal house to house searches, and extra judicial killings before we take seriously what it actually means, that carbon life forms will no longer have a monopoly on intelligence. (man I love that line)

Sorry for the long comment - re: the AI section I vote keep it in but move it to a later section so as to flow with the established narrative better vs. being a bit interruptive to it.  Alternatively: Keep in a paragraph or two on the topic, and hyperlink off to a deeper story that is published on Medium - I know Paula would love to help Santi expand further on the topic.

**Comment by santisiri** [comment]
i did exactly what @SFSandra suggested today. and literally elon musk started fighting mark zuckerberg exactly about this in public *today*: https://twitter.com/elonmusk/status/889743782387761152

a.i. is *the* issue pressing for digital governance and it will be a very relevant topic in the years to come. i disagree with @dwightmwilson and @piamancini here: we have a responsibility on explaining this new world to our readers and supporters. I did tone down the epic behind this and put it on a more neutral way.

**Comment by santisiri** [comment]
If no further comments

**Pull request closed without merging**
